### ISSUE TITLE
测试了一下vless+tls可以,但是 xtls-rprx-vision + reality有问题

### ISSUE THREAD

**Issue by ClashUS** [wyx2685/XrayR#3]
测试了一下vless+tls可以,但是 xtls-rprx-vision + reality有问题.
v2b 下发到 shadowsrocket 的字段 vless-flow 是 none 而不是 xtls-rprx-vision, 我在 小火箭里手动修正为 xtls-rprx-vision 也无法连接.
我猜是 xraryr 的问题了.
```
#xrayr 跟换 NodeID  CertDomain ,
Log:
  Level: warning # Log level: none, error, warning, info, debug 
  AccessPath: # /etc/XrayR/access.Log
  ErrorPath: # /etc/XrayR/error.log
DnsConfigPath: # /etc/XrayR/dns.json # Path to dns config, check https://xtls.github.io/config/dns.html for help
RouteConfigPath: # /etc/XrayR/route.json # Path to route config, check https://xtls.github.io/config/routing.html for help
InboundConfigPath: # /etc/XrayR/custom_inbound.json # Path to custom inbound config, check https://xtls.github.io/config/inbound.html for help
OutboundConfigPath: # /etc/XrayR/custom_outbound.json # Path to custom outbound config, check https://xtls.github.io/config/outbound.html for help
ConnectionConfig:
  Handshake: 4 # Handshake time limit, Second
  ConnIdle: 30 # Connection idle time limit, Second
  UplinkOnly: 2 # Time limit when the connection downstream is closed, Second
  DownlinkOnly: 4 # Time limit when the connection is closed after the uplink is closed, Second
  BufferSize: 64 # The internal cache size of each connection, kB
Nodes:
 -
    PanelType: "NewV2board" # Panel type: SSpanel, V2board, NewV2board, PMpanel, Proxypanel, V2RaySocks
    ApiConfig:
      ApiHost: https://baidu.com
      ApiKey: bd123.
      NodeID: 3  
      NodeType: V2ray # Node type: V2ray, Shadowsocks, Trojan, Shadowsocks-Plugin
      Timeout: 30 # Timeout for the api request
      EnableVless: true # Enable Vless for V2ray Type
      VlessFlow: "xtls-rprx-vision" # Only support vless
      SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
      DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
      RuleListPath: # /etc/XrayR/rulelist Path to local rulelist file
    ControllerConfig:
      ListenIP: 0.0.0.0 # IP address you want to listen
      SendIP: 0.0.0.0 # IP address you want to send pacakage
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
      EnableProxyProtocol: false # Only works for WebSocket and TCP
      EnableFallback: false # Only support for Trojan and Vless
      EnableREALITY: true # Enable REALITY
      REALITYConfigs:
        Show: true # Show REALITY debug
        Dest: download.nvidia.com:443 # Required, Same as fallback
        ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for disable
        ServerNames: # Required, list of available serverNames for the client, * wildcard is not supported at the moment.
          - download.nvidia.com
        PrivateKey: # 可不填
        MinClientVer: # Optional, minimum version of Xray client, format is x.y.z.
        MaxClientVer: # Optional, maximum version of Xray client, format is x.y.z.
        MaxTimeDiff: 0 # Optional, maximum allowed time difference, unit is in milliseconds.
        ShortIds: # 可不填

      CertConfig:
        CertMode: none # Option about how to get certificate: none, file, http, tls, dns. Choose "none" will forcedly disable the tls config.

```

xrayr 关键日志
```
Aug 21 23:14:35  XrayR[1163063]: REALITY remoteAddr: 112.97.201.102:63976
Aug 21 23:14:35 XrayR[1163063]: REALITY remoteAddr: 112.97.201.102:63976        hs.c.AuthKey[:16]: [95 58 170 125 190 215 204 89 54 96 72 188 178 128 227 90]        AEAD: *aes.gcmAsm
Aug 21 23:14:35 XrayR[1163063]: REALITY remoteAddr: 112.97.201.102:63976        hs.c.ClientVer: [1 8 1]
Aug 21 23:14:35 XrayR[1163063]: REALITY remoteAddr: 112.97.201.102:63976        hs.c.ClientTime: 2023-08-21 23:14:35 +0800 CST
Aug 21 23:14:35 XrayR[1163063]: REALITY remoteAddr: 112.97.201.102:63976        hs.c.ClientShortId: [168 216 214 131 0 0 0 0]
Aug 21 23:14:35 XrayR[1163063]: REALITY remoteAddr: 112.97.201.102:63976        hs.c.conn == conn: true
Aug 21 23:14:35 XrayR[1163063]: REALITY remoteAddr: 112.97.201.102:63976        len(s2cSaved): 99        Server Hello: 93
Aug 21 23:14:35 XrayR[1163063]: REALITY remoteAddr: 112.97.201.102:63976        handled: false
```
